### ISSUE TITLE
Support creation of Business entity

### ISSUE THREAD

**Issue by algodave** [justifi-tech/justifi-ruby#48]
We need to upgrade our existing [Hosted Onboarding](https://docs.justifi.tech/api-spec#tag/Hosted-Onboarding) flow, and avoid the upcoming deprecation:

>  _Passing a `sub_account_id` to the iframe instead of a `business_id` is still supported but will be deprecated soon_

As the docs say, we will need to create a `Business` entity, but that's not currently supported by this Ruby gem.

**Comment by pete2786** [comment]
Thanks, we will add this.

**Comment by pete2786** [comment]
Released version 0.9.0 with this feature.
